### ISSUE TITLE
[Bug} Crash with wizardry utils

### ISSUE THREAD

**Issue by Ironsasquatch3345** [WinDanesz/RiseOfTheAnimagus#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Observed behaviour

installed new version of morph spellpack went to start minecraft and the game crashed.

### Expected behaviour

The game should run properly

### Steps to reproduce

1. install morphspellpack
2. try to start the game
3. watch the game crash

### Crashlog

https://gist.github.com/Ironsasquatch3345/a61f76cdf44d2cb5e7dcb2d82c084bcc

### Environment (Singleplayer/Server, etc.)

Singleplayer

### Mod version

1.2.0

### Forge version

1.12.2 14.23.5.2859

### Other mods

Crash report included

**Comment by WinDanesz** [comment]
Update WizardryUtils to v1.2.3
